# -*- coding: utf-8 -*-
"""Practice with custom modules .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hnFa687OYeRBYqgKnpvqQb4UKmSICoL
"""

pip install torch

import torch
import torch.nn as nn

class LR(nn.Module):
  def __init__(self,input_size,output_size):
  #contructor init
  #self -instance of the class yet to be initialised
    super().__init__()
    self.linear=nn.Linear(input_size,output_size)
  def forward(self,x):
    pred=self.linear(x)
    return pred

torch.manual_seed(1)
model=LR(1,2)
x=torch.tensor([1.0])
print(model.forward(x))

