# -*- coding: utf-8 -*-
"""Practice with manual_seed .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hnFa687OYeRBYqgKnpvqQb4UKmSICoL
"""

pip install torch

import torch

from torch.nn import Linear

torch.manual_seed(10)
#Assign random values using seed
model=Linear(in_features=1,out_features=1)
print(model.bias,model.weight)

x=torch.tensor([[2.0],[3.3]])
print(model(x))

